# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.
[kube_control_plane]
node1 ansible_host=51.250.82.94 ansible_user=ubuntu ansible_ssh_private_key_file=/home/user/.ssh/for_yandex

[etcd:children]
kube_control_plane

[kube_node]
node2 ansible_host=111.88.243.88 ansible_user=ubuntu ansible_ssh_private_key_file=/home/user/.ssh/for_yandex
node3 ansible_host=111.88.245.179 ansible_user=ubuntu ansible_ssh_private_key_file=/home/user/.ssh/for_yandex
node4 ansible_host=46.21.244.100 ansible_user=ubuntu ansible_ssh_private_key_file=/home/user/.ssh/for_yandex
node5 ansible_host=89.169.141.232 ansible_user=ubuntu ansible_ssh_private_key_file=/home/user/.ssh/for_yandex
